### ISSUE TITLE
Some programs are not executed under wayland/sway

### ISSUE THREAD

**Issue by aiufeh** [tobi-wan-kenobi/bumblebee-status#628] opened 2020-05-14 08:47 UTC
#### Summary
Trying to execute a command on left click doesn't seem to work with all kind of programs. The click event is noticed but the command returns an empty state. Trying to execute a command with alacritty which runs fine results in a wayland error.

#### Description:
I tried to execute a command on left click, with this: 
```status_command bumblebee-status -d -m disk:home -p disk.left-click="dolphin"``` 

Some programs work fine like `firefox` or `alacritty`, other programs like `dolphin` or `konsole` or `pavucontrol` don't start. The debug output states:
```
[2020-05-14 11:41:52,197] DEBUG    starting click event processing
[2020-05-14 11:41:52,198] DEBUG    new event: [
[2020-05-14 11:41:52,879] DEBUG    new event: { "name": "home", "instance": "39f3a57e-bfb9-4fff-8ea5-3154bc71b9f5", "button": 1, "event": 272, "x": 2447, "y": 8, "relative_x": 164, "relative_y": 8, "width": 274, "height": 24 }
[2020-05-14 11:41:52,879] INFO     executing command 'dolphin {instance}'
[2020-05-14 11:41:52,880] INFO     command returned ''
``` 
I tried to execute a program via alacritty with: `disk.left-click="alacritty -e dolphin"` but received the following error: `The wayland connection experienced a fatal error: bad file descriptor`

#### How to reproduce
Executing programs with bumblebee-status using sway.

**Comment by tobi-wan-kenobi** [comment] 2020-05-14 18:26
That is weird, and I am not sure how that could happen specifically to sway, because the functionality is generically Python.

One thing that comes to mind: *IF* you use aliases for modules, you *need* to specify the parameter to their alias, like this:

`bumblebee-status -d -m disk:home -p home.left-click="dolphin"`

I.e. "home.left-click" instead of "disk.left-click" Is that possibly the source of the issue?

Cheers

**Comment by aiufeh** [comment] 2020-05-15 06:51
Thank you for your response. Unfortunately that doesn't fix the problem. I don't have aliases for modules other than disk. Everything works fine with the exact same configuration on x11 though.

**Comment by tobi-wan-kenobi** [comment] 2020-05-15 07:52
That is really strange. The only thing I can think of is that maybe sway sanitizes the environment somehow - can you try to provide the full path to the binary instead of just the name?

Also, you *could* try the "development" branch, which is pretty stable by now, and uses a different way to execute programs internally, maybe that helps.

**Comment by aiufeh** [comment] 2020-05-15 12:15
I tried your approaches, unfortunately they didn't help. In the development version even the programs that worked (e.g. firefox and alacritty) are not being executed. This is the debug log of the command `status-command bumblebee-status -d -m pasink -p pasink.right-click="pavucontrol"` under X11 and Wayland in the development version.

X11:
```
[2020-05-15 13:59:48,983] cli              DEBUG    pactl info
[2020-05-15 13:59:48,989] cli              DEBUG    pactl list sinks
[2020-05-15 13:59:49,298] bumblebee-status INFO     input event: {"name":"pasink","instance":"2a33222e-e2df-4f93-9a2e-eccb74cea9e7","button":3,"modifiers":[],"x":2489,"y":13,"relative_x":28,"relative_y":13,"width":99,"height":24}
[2020-05-15 13:59:49,298] cli              DEBUG    pavucontrol
```
Wayland: 
```
[2020-05-15 13:56:06,321] cli              DEBUG    pactl info
[2020-05-15 13:56:06,327] cli              DEBUG    pactl list sinks
[2020-05-15 13:56:06,750] bumblebee-status INFO     input event: { "name": "pasink", "instance": "74cf1345-ef97-48f6-9462-09cc580d1362", "button": 3, "event": 273, "x": 2511, "y": 15, "relative_x": 53, "relative_y": 15, "width": 99, "height": 24 }
[2020-05-15 13:56:06,750] cli              DEBUG    pavucontrol
```
They are almost the same, just that in the x11 version the "event" has changed to "modifiers".

Add: I get an `name: 'Exceptions' is not defined'` error when using the battery module in the development version.

**Comment by tobi-wan-kenobi** [comment] 2020-05-15 17:49
Fixed the battery module, thanks for reporting!

**Comment by tobi-wan-kenobi** [comment] 2020-05-15 18:00
Also, looking at the "development" code, you spotted missing implementation - the custom input event handlers were missing, I have added them now.

If you don't mind, I'd appreciate it a lot if you could give the development branch another go, I hope it fixes your issue (at least for me, alacritty starts fine, and the event output looks exactly identical to what you have, even though I'm using X11).

**Comment by aiufeh** [comment] 2020-05-15 20:08
At least `firefox` and `alacritty` are running again. The initial error with `dolphin` and `pavucontrol` remains. I tested your `util.cli.execute` method with the named programs and they started without any problems.

**Comment by aiufeh** [comment] 2020-05-15 21:42
I think I found the root of the problem. Under Wayland it seems not possible to run a graphical application as root. For example if I configure the click event to something like `sudo -i -H -u $USER pavucontrol` the program gets executed (there are other problems though, like pavucontrol unable to connect to the pulseaudio server running it this way).

For Reference:
https://bugzilla.redhat.com/show_bug.cgi?id=1370324#c3
https://wiki.archlinux.org/index.php/Running_GUI_applications_as_root

A possible solution could be something like that (a little bit hacky though):
https://stackoverflow.com/questions/1770209/run-child-processes-as-different-user-from-a-long-running-python-process/6037494#6037494

**Comment by tobi-wan-kenobi** [comment] 2020-05-16 02:52
Interesting! But I have to admit I don't get why firefox and alacritty work, then. 

Also, why is bumblebee-status running in a root context?

It usually should be started as the logged in user.

⁣Couls you maybe briefly outline your setup? I'd really like to be able to reproc this issue :-)

**Comment by aiufeh** [comment] 2020-05-16 07:35
I seemingly got a little confused yesterday. You are right, the status_bar runs as the logged in user and not as root (luckily). But now I am even more confused since the `sudo` user change command worked.

**Comment by tobi-wan-kenobi** [comment] 2020-05-16 09:40
OK, that is *very* weird, but I have a suspicion. Maybe the problem is that, by default, bumblebee-status does *not* invoke a new shell for such commands. Using "sudo" would work around that, I believe.
I'll update the development branch right away to execute a new subshell, it would be great if you could let me know whether that fixes the issue for you.

**Comment by aiufeh** [comment] 2020-05-16 12:16
The problem remains under Wayland. Under x11 now the given command gets executed twice^^

**Comment by tobi-wan-kenobi** [comment] 2020-05-16 13:06
Hm, that's not what I (or the corresponding unit test) see. 

Can you please give me your *exact* bumblebee-status invocation line?

One suspicion: If we are talking about a pulseaudio module in particular, that already has a default left-click bind to pavucontrol. If you add a manual config to that, it'd execute twice.

**Comment by tobi-wan-kenobi** [comment] 2020-05-16 13:18
To further debug the issue, I have added more logging to the CLI module (in "development"), and a way to run commands in the foreground instead of the background (that freezes your module until the application exits, but gives you more debug output).

You can use it like this:

`bumblebee-status -m spacer -p spacer.text=alacritty spacer.left-click=alacritty spacer.left-click-wait=true --debug 2> ~/bumblebee.log`

If you could give me that debug log as well, that would help me a lot.

Many thanks in advance!

**Comment by aiufeh** [comment] 2020-05-16 14:25
I used the status command you provided for pavucontrol (and dolphin):
```
set $status bumblebee-status \
        -m spacer \
        -p spacer.text=alacritty spacer.left-click=pavucontrol \
        spacer.left-click-wait=true --debug 2> /home/aiufeh/bumblebee.log
```
And in the sway configs bar section:
```
status_command $status
```
Now I get an error code after all:
```
[2020-05-16 18:18:42,529] bumblebee-status INFO     input event: { "name": "spacer", "instance": "ed2efe72-f94f-4896-8451-b4109256bc5b", "button": 1, "event": 272, "x": 2484, "y": 14, "relative_x": 26, "relative_y": 14, "width": 99, "height": 24 }
[2020-05-16 18:18:42,529] cli              DEBUG    pavucontrol
[2020-05-16 18:18:42,811] cli              WARNING  pavucontrol exited with code -6
[2020-05-16 18:18:42,811] input            ERROR    failed to invoke callback: pavucontrol exited with code -6
```
Thank you for all your support and focus!, bumblebee-status is great! :)

**Comment by aiufeh** [comment] 2020-05-16 14:29
Under x11 it works fine (also starts only one instance as it should):
```
[2020-05-16 18:28:09,154] bumblebee-status INFO     input event: {"name":"spacer","instance":"bfb695f9-a146-49b9-942f-0dc5b0d431a6","button":1,"modifiers":[],"x":2538,"y":0,"relative_x":77,"relative_y":0,"width":99,"height":24}
[2020-05-16 18:28:09,154] cli              DEBUG    pavucontrol
[2020-05-16 18:28:13,113] cli              DEBUG
```

**Comment by tobi-wan-kenobi** [comment] 2020-05-16 14:51
I believe exit code 6 typically means that the application triggered an assertion and was aborted.

Does pavucontrol get triggered when you invoke it from a terminal? Also, what's your login shell? That might also give an indication what goes wrong, because Python uses /bin/sh by default, i think.

⁣Sent from TypeApp ​

**Comment by tobi-wan-kenobi** [comment] 2020-05-16 14:52
Also, thanks a lot for the kind words! Sorry that this issue is dragging on a bit... Not being able to reproduce makes it hard to come up with useful ideas :-)

**Comment by aiufeh** [comment] 2020-05-16 15:20
Yes, pavucontrol gets triggered from `konsole` and from `alacritty` under Wayland. My login shell is `zsh`, but I tested it successfully with `bash` and `sh`, too.

**Comment by piyueh** [comment] 2020-06-27 11:53
I dug this a little bit because I was intrigued. I only tried with `pavucontrol`. Not sure the root cause, but I can confirm this: by adding `env["GDK_BACKEND"] = "x11"` in `util.cli.execute` (before calling `subprocess.Popen`), `pavucontrol` worked on my machine. This forces `pavucontrol` to run under XWayland, instead of native Wayland. This is indeed weird, though, because `pavucontrol` is supposed to run under native Wayland.

BTW, I think [here](https://github.com/tobi-wan-kenobi/bumblebee-status/blob/1484109fe07b78f605278bdac22921749e36e604/bumblebee_status/util/cli.py#L50) we shouldn't omit the stderr output? Otherwise, we will miss errors if the target program relies on stderr to provide debug info.

**Comment by piyueh** [comment] 2020-06-27 12:16
The environment variables are definitely different when `bumblebee-status` execute the command. I did a quick test:

1. pickle and dump the current `os.environ` in a normal python session (the one that `Popen` can launch `pavucontrol`) to somewhere
2. in `util.cli.execute`, before `subprocess.Popen`, read in that working set of environment variables into the `env` used by `subprocess.Popen`.
3. restart sway with `$ swaymsg "reload"` (don't logout/reboot; need to keep the environment the same)
4. left click on `disk` widget now launches `pavucontrol`

So it's definitely some environment variables missing in `bumblebee-status`'s own session (or whatever it's called). I'll try to dig deeper tomorrow.

**Comment by tobi-wan-kenobi** [comment] 2020-06-27 13:00
@piyueh That is very interesting, thanks!

Could you please give me the working vs. the non-working set of environment variables?

Also, copying the environment in `util.cli.execute` from `os.environ` was implemented only a couple of days ago - so is it possible that the bug is gone by now?

**Comment by piyueh** [comment] 2020-06-28 07:13
The issue still exists with the current `main` branch (commit 350648b).

I narrowed down the environment variable that caused the issue at least on my machine, which is `WAYLAND_SOCKET`. After I deleted `WAYLAND_SOCKET` from `env` in `util.cli.execute`, I could launch `pavucontrol` with a left mouse click. That is, do:

```
del env["WAYLAND_SOCKET"]
```
after [line 36 in `util/cli.py`](https://github.com/tobi-wan-kenobi/bumblebee-status/blob/350648b0cd9e3c3b980c6e72946ddfc8d14cb11f/bumblebee_status/util/cli.py#L36) and before the `subprocess.Popen` call.

I don't really understand how window manager and Sway work, so I'm not sure what `WAYLAND_SOCKET` is for. But `WAYLAND_SOCKET` does not exist in my Sway desktop session. Not sure why `bumblebee-status`'s environment has that variable. Also, I only tested with `pavucontrol`.

**Comment by piyueh** [comment] 2020-06-28 07:24
### Update

I believe this issue is from Sway itself and is fixed in the current `master` branch of Sway through [this PR](https://github.com/swaywm/sway/pull/5440).

I tried the `mater` branch of Sway and with the `main` branch of `bumblebee-status`, it's working well now: at least `pavucontrol` can be launched from a left click without modifying any code in `bumblebee-status`.

**Comment by tobi-wan-kenobi** [comment] 2020-06-28 08:41
@piyueh Thanks for the great findings, that is really good to knoq!

I'll go ahead and implement a workaround in bumblebee that deletes that key, if it exists.

**Closed** 2020-06-28 08:45 UTC
Labels: bug
