### ISSUE TITLE
Sometime CPU module freezes

### ISSUE THREAD

**Issue by HappyCthulhu** [tobi-wan-kenobi/bumblebee-status#935] opened 2022-10-17 08:17 UTC
#### Description
Affected module: CPU
Version used: AUR

<description>

#### How to reproduce
Idk why its happening. I just wanna tell, that sometimes this happening. So, in rare cases, CPU module "freeze". I mean, he is showing constant value. And dont change it. For changing it, u need to reload i3. Maybe in future i will be able to tell u, why and in which cases its happening.

**Comment by tobi-wan-kenobi** [comment] 2022-10-17 18:03
I had a look at the code and the only thing I can think of is an exception in psutil, and even that would probably just cause an error.

I will research (=google) some more, but right now, I have no idea what could cause this.

**Comment by HappyCthulhu** [comment] 2022-10-24 09:36
it reproducing rn. Right in current moment. What can i do, to help u find the root of this issue? Pls respond quick, im not reloading my pc, bc bug will dissapear

**Comment by tobi-wan-kenobi** [comment] 2022-10-24 09:47
are all the other modules also stuck? how is cpu util. of bumblebee in "ps aux"?

does clicking on the module help?

**Comment by HappyCthulhu** [comment] 2022-10-24 09:55
hmmm. yes, i think, other modules stuck 2. ram module stuck for sure. i think, time module 2.  I can reach to volume module. I mean, it changes value of volume, if trying to change it.

Yes, clicking on CPU module helped. So, i cant test it rn, bc bug is done for now)


![image](https://user-images.githubusercontent.com/23531195/197500002-c18c1fbf-ff4b-4fe8-9b3a-57c61bd0a1da.png)

**Comment by tobi-wan-kenobi** [comment] 2022-10-24 10:17
got it, that still helps me, i think. thanks!

**Comment by tobi-wan-kenobi** [comment] 2022-11-19 09:19
just to clarify that i am not ignoring this:

i have tried a lot of things to reproduce this, but the only sensible idea i can come up with is that the module does not receive updates anymore (and since other modules still work, i have zero idea how this is possible)

the module code is extremely simple, so i guess it has to be the framework. but only cpu is affected, which is weird.

so: sorry, i *am* still investigating, but it is an elusive issue.

**Comment by tobi-wan-kenobi** [comment] 2023-09-15 13:22
Closing as "cannot reproduce". Please reopen if the issue persists.

**Closed by tobi-wan-kenobi** 2023-09-15 13:22 UTC
