### ISSUE TITLE
changing fonts doesn

### ISSUE THREAD

**Issue by StepanKomis** [tobi-wan-kenobi/bumblebee-status#984] opened 2023-08-22 15:18 UTC
Affected module: <module name>

Description:
<description>

If you are having problems with fonts, please read:
https://github.com/tobi-wan-kenobi/bumblebee-status/issues/228
https://github.com/tobi-wan-kenobi/bumblebee-status/issues/210
https://github.com/tobi-wan-kenobi/bumblebee-status/issues/197
https://github.com/tobi-wan-kenobi/bumblebee-status/issues/233

Please note FontAwesome 5 is currently not supported:
https://github.com/tobi-wan-kenobi/bumblebee-status/issues/239

**Comment by tobi-wan-kenobi** [comment] 2023-09-11 07:43
Closing as potential duplicate of #985

**Closed as completed by tobi-wan-kenobi** 2023-09-11 07:43 UTC
