### ISSUE TITLE
amdgpu_bl0 change to amdgpu_bl1 and 0

### ISSUE THREAD

**Issue by pypeetpy** [tobi-wan-kenobi/bumblebee-status#492] opened 2019-12-22 12:49 UTC
#### Summary
Affected module: <module name>

#### Description:
<description>

**Comment by tobi-wan-kenobi** [comment] 2019-12-22 13:26
I'd be grateful if you could elaborate a bit - which module is affected, and what's the actual problem?

Thanks!

**Comment by pypeetpy** [comment] 2019-12-22 14:19
brightness module

**Comment by tobi-wan-kenobi** [comment] 2019-12-23 12:29
I still don't get the issue. The "brightness" module does not change device names, and it exclusively uses "xbacklight", "brightnessctl" or "light" (whichever tool you have installed) to adjust brightness.

Please try to describe your issue in a bit more detail, otherwise I will have to close this ticket, because I am unable to reproduce it.

**Comment by pypeetpy** [comment] 2019-12-23 12:57
sorry , my laptop is ryzen cpu and the file in /sys/class/backlight/amdgpu_bl0 will change in some time I boot up or reboot the laptop , so if I write amdgpu_bl0 to /usr/share/bumblebee-status/modules/brightness.py when the system change to amdgpu_bl1, the brightness module will not work.

**Closed** 2019-12-24 13:00 UTC

**Comment by tobi-wan-kenobi** [comment] 2019-12-24 13:01
OK, *now* I got the issue, thanks for explaining!

That should be straight-forward to fix. I've added code to the brightness module in master that adds simple wildcard support. you can now specify the device path as /sys/class/backlight/amdgpu* and it will take the first path that matches the wildcard.

I hope this solves your issue!

**Comment by pypeetpy** [comment] 2019-12-24 13:34
> OK, _now_ I got the issue, thanks for explaining!
> 
> That should be straight-forward to fix. I've added code to the brightness module in master that adds simple wildcard support. you can now specify the device path as /sys/class/backlight/amdgpu* and it will take the first path that matches the wildcard.
> 
> I hope this solves your issue!

thank you for your help, I have change as you tell me to , /sys/class/backlight/amdgpu* , the brightness module is show n/a now.

**Comment by tobi-wan-kenobi** [comment] 2019-12-24 13:37
Can you please show me the exact invocation/commandline you are using? You probably need to put the path in quotes.

**Comment by pypeetpy** [comment] 2019-12-24 13:54
> Can you please show me the exact invocation/commandline you are using? You probably need to put the path in quotes.
> […](#)
> On Dec 24, 2019, 14:34, at 14:34, pypeetpy ***@***.***> wrote: > OK, _now_ I got the issue, thanks for explaining! > > That should be straight-forward to fix. I've added code to the brightness module in master that adds simple wildcard support. you can now specify the device path as /sys/class/backlight/amdgpu* and it will take the first path that matches the wildcard. > > I hope this solves your issue! thank you for your help, I have change as you tell me to , /sys/class/backlight/amdgpu* , the brightness module is show n/a now. -- You are receiving this because you modified the open/close state. Reply to this email directly or view it on GitHub: [#492 (comment)](https://github.com/tobi-wan-kenobi/bumblebee-status/issues/492#issuecomment-568749542)

![2019-12-24_20-53](https://user-images.githubusercontent.com/59130593/71415700-96c6a100-268f-11ea-9914-60666e0b5f63.png)
