### ISSUE TITLE
Formatting Disk & Memory at the same time not possible

### ISSUE THREAD

**Issue by nemhods** [tobi-wan-kenobi/bumblebee-status#362] opened 2019-02-14 21:49 UTC
#### Summary
Affected module: <disk/memory>

Description:
When using command-line parameters to format both disk and the memory module, only the latest parameter will be applied. The other parameter will revert to default.

#### How to reproduce
run
`bumblebee-status -m memory disk -p memory.format="{percent}" -p disk.format="{percent}"`
and observe that only the disk output gets formatted:
```
{"version": 1, "click_events": true}
[
[{"full_text": " ram 1.80GiB/11.63GiB (15.50%) ", "color": "#aabbcc", "background": null, "separator_block_width": null, "separator": true, "min_width": null, "align": null, "instance": "6ca70203-0670-45cc-ba97-7e02ee60ab75", "name": "memory"}, {"full_text": " hdd 51.52918335523705 ", "color": "#aabbcc", "background": null, "separator_block_width": null, "separator": true, "min_width": null, "align": null, "instance": "a7b8fdfd-fa6f-44c2-8027-4e985e852c0a", "name": "disk"}],
```

However, providing the configuration options in reverse order
`bumblebee-status -m memory disk -p disk.format="{percent}" -p memory.format="{percent}"     `      
formats memory but not disk:
```
{"version": 1, "click_events": true}
[
[{"full_text": " ram 16.70596604612367 ", "color": "#aabbcc", "background": null, "separator_block_width": null, "separator": true, "min_width": null, "align": null, "instance": "fec2c100-dcd4-45bb-a69d-f0b8c93a48b3", "name": "memory"}, {"full_text": " hdd 112.63GiB/218.56GiB (51.53%) ", "color": "#aabbcc", "background": null, "separator_block_width": null, "separator": true, "min_width": null, "align": null, "instance": "658008bf-5887-431b-92ab-617a7ec74454", "name": "disk"}],
```

#### Expected behavior
I expected both the memory and the disk formatting option to be applied at the same time, regardless of order.

**Comment by tobi-wan-kenobi** [comment] 2019-02-15 16:54
Hi,

I think this is a duplicate of #357. You must only specify `-p` once. But since this is the second time this is raised as bug, I'll investigate whether it's possible to parse the parameters a bit more flexibly.

Thanks for bringing this up & I hope this fixes your issue!

**Closed** 2019-02-15 17:02 UTC

**Comment by nemhods** [comment] 2019-02-15 21:03
Ahh I understand! Appreciate the heads up.
Thanks for your work!
