### ISSUE TITLE
Problem with powerline themes 

### ISSUE THREAD

**Issue by GreyDireWolf** [tobi-wan-kenobi/bumblebee-status#233] opened 2018-02-18 07:54 UTC
Recently after updating my arch system bumblebee's all powerline themes show lot of garbage on bar. Normal non-powerline themes are working fine
![2018-02-18-131445_1076x20_scrot](https://user-images.githubusercontent.com/13380243/36349516-cd80a55a-14ae-11e8-9958-9528746073b3.png)

**Comment by tobi-wan-kenobi** [comment] 2018-02-18 17:42
Hi,

which version of bumblebee-status are you using? The AUR release, the AUR git or something else?

I seem to remember that this was an issue for a short term, but in the latest versions, this should be resolved.

Also, could you please check whether you have a `~/.config/bumblebee-status/status.json` file? If so, deleting it might resolve the issue.

Thanks!

**Comment by GreyDireWolf** [comment] 2018-02-19 19:42
I'm using latest git version

**Comment by tobi-wan-kenobi** [comment] 2018-02-20 17:51
That's strange, my setup is exactly the same (latest git, obviously, and Arch).

Could you please let me know your `status` line in `~/.config/i3/config`, and maybe a sample output of running the command manually in the terminal?

Sorry for the inconvenience!

**Comment by GreyDireWolf** [comment] 2018-02-21 08:15
My status command is ```bumblebee-status -m pasink battery nic disk datetime -p disk.path=/home datetime.forma t="%a,%b%d,%Y at %I:%M %p" nic.exclude="enp14s0,wlp2s0" -t solarized-powerline``` and output after running in terminal is 
```[wolf@amey ~]$ bumblebee-status 
failed to import taskwarrior: argument of type 'FileNotFoundError' is not iterable
{"version": 1, "click_events": true}
[
[],
[],
```

**Comment by tobi-wan-kenobi** [comment] 2018-02-24 10:54
Hi,

that looks OK, as far as I can tell. Can you please let me know the font(s) you're using in the `bar` section of your i3 config?

Sorry that this takes so long to resolve.

**Comment by GreyDireWolf** [comment] 2018-02-25 13:36
Thanks for the quick response. Well I haven't specified any font in bar section. I'm using powerline patched Hack font for i3 though

**Comment by tobi-wan-kenobi** [comment] 2018-02-25 13:40
In that case, could you please try to explicitly specify a font?

Maybe it is related to the glyphs in the font. To check that, could you please try to use Inconsolata? That font works fine for me on Arch.

Thanks!

⁣Sent from TypeApp ​

**Comment by GreyDireWolf** [comment] 2018-02-25 13:41
Ok i explicitly specified powerline patched pango:hack and Inconsolata fonts in bar section. Still same problem occurs

**Comment by tobi-wan-kenobi** [comment] 2018-02-25 13:49
Hm, the screenshot looks as if unicode chars are added before and after each icon, but not the separator arrows. Also, the theme looks custom. Did you modify also the icons.json file? 

Also, do you use ~/.config/bumblebee-status/themes/ directory?

If so, could you please verify which files it contains, and whether they differ from the github repo. In case of duplicates, the data from ~/.config will be used, iirc

⁣Sent from TypeApp ​

**Comment by leskeg** [comment] 2018-02-26 19:46
I faced same problem on Arch Linux. I've fixed installing ```awesome-terminal-fonts```

**Comment by GreyDireWolf** [comment] 2018-02-27 17:01
@leskeg How did you specify name of the font in config file? I install awesome-terminal-font with pacman but I'm having trouble with specifying the name of the font.

**Comment by GreyDireWolf** [comment] 2018-02-27 17:04
@tobi-wan-kenobi I didn't modify icons.json. Previously I used `~/Apps/bumblebee-status/themes` directly. After powerline themes broke I removed that directory and installed `bumblebee-status-git` from aur.

**Comment by tobi-wan-kenobi** [comment] 2018-02-27 17:13
@GreyDireWolf damn :(

I've just tried to reproduce the issue by installing `bumblebee-status-git`, but for me, it works fine with the following configuration:

```
bar {
        output VGA-1
        font pango:Inconsolata 12
        position top
        tray_output none
        status_command /usr/bin/bumblebee-status -m nic disk:/ load cpu memory battery date time pasink pasource brightness -p time.format="%H:%M CW %V" date.format="%a, %b %d %Y"  -t solarized-powerline
....
}
```

**Comment by tobi-wan-kenobi** [comment] 2018-02-27 17:13
Just a very stupid question, but is it possible that you are missing the font you've configured in `bar`?

I.e., in my case:
```
$ pacman -Ss inconsolata
community/ttf-inconsolata 1:2.0.0.1-2 [installed]
    Monospace font for pretty code listings and for the terminal
```

**Comment by mfcarneiro** [comment] 2018-03-02 14:00
@leskeg Leskeg Thanks for your help, I faced the same problem, but the only icon that works is the cpu, all the rest are having the same "bug" icon.
I just installed the awesome-terminal-fonts and restart i3wm and works! 

Thanks a lot!

**Comment by GreyDireWolf** [comment] 2018-03-03 11:16
@tobi-wan-kenobi Thanks for the configuration. I didn't mention `output` which in my case in `LVDS`. After mentioning it in `bar` section problem seems to be resolved

**Comment by tobi-wan-kenobi** [comment] 2018-03-04 07:28
Perfect, glad to read that!
Guess I've learned something about i3 again :)

**Closed by tobi-wan-kenobi** 2018-03-04 07:28 UTC
Labels: bug

**Comment by aannaldo** [comment] 2020-04-24 02:18
I'm on Debian so don't have access to awesome-terminal-fonts. I've tried everything in all of these font threads, but am having specific difficulty with the clock icon and the volume icon specifically. 

![image](https://user-images.githubusercontent.com/43480206/80168210-46653e80-85b0-11ea-96de-4862c4c182f9.png)


I have powerline fonts installed and am using Inconsolata for Powerline specifically. I've tried using PowerlineSymbols and FontAwesome as backups (as well as every permutation order-wise) with no luck. If I specify FontAwesome first, however, the icons show up but then the text reverts back to the default font for my machine and my powerline symbols break.

**Comment by tobi-wan-kenobi** [comment] 2020-04-24 14:07
Is it possible that Inconsolata-for-Powerline is using the Awesome Font version 5? That one is missing some important glyphs that have been moved to the paid version of Awesome Font, as far as I am aware.

**Comment by aannaldo** [comment] 2020-04-24 21:16
That is possible, but the Font Awesome version I set as a fallback uses version 4. It sort of seems like the fallback fonts aren't having an effect at all. Because if I set FontAwesome as the primary and Inconsolata for Powerline as the secondary, I see the correct glyphs, but then I'm missing the powerline arrows.

**Comment by tobi-wan-kenobi** [comment] 2020-04-25 08:26
:thinking: Can you maybe show me how you configured the fallback fonts in your i3 config?

**Comment by aannaldo** [comment] 2020-04-25 20:31
Sure. 
![image](https://user-images.githubusercontent.com/43480206/80290264-36fe0680-8712-11ea-8fbb-817700f28648.png)

**Comment by tobi-wan-kenobi** [comment] 2020-04-26 08:01
I'm not sure this is how the fallback fonts for i3 work. I *think* you have to specify them in a single line, such as:

`font pango:Inconsolata for Powerline 10, FontAwesome 10`

Could you give that a try, please?

**Comment by aannaldo** [comment] 2020-04-26 17:47
Sure. I get the same behavior:
![image](https://user-images.githubusercontent.com/43480206/80315281-7422d100-87c4-11ea-9222-15ee9aeea7dc.png)

**Comment by airpods69** [comment] 2023-02-20 04:47
Doesn't look like the issue got fixed even after changing the fonts to Inconsolata and reverting fonts awesome from v5 to v4.

**Comment by tobi-wan-kenobi** [comment] 2023-02-20 05:28
The font in the i3 config needs to be a patched powerline font (e.g. nerdfonts).

I can confirm it *does* work (with Hack for Powerline, at least), as Arch is my daily driver.

If you post your i3 config (the bar stuff), we cn investigate.

Cheers!

**Comment by airpods69** [comment] 2023-02-20 05:40
what do you mean by "Hack for Powerline"? (I might be confusing it with the literal meaning of Hack XD)  

and the bar config:

```bar {
	font pango: Inconsolata 10
        modifier $Mod
	position top
	tray_output none
	status_command bumblebee-status -m hostname nic cpu \
		memory battery brightness date time \
		-p time.format="%H:%M" date.format="%a, %b %d %Y" brightness.step=5 \
		-p battery.warning=30 \
		-t nord-powerline
}```

I had `Roboto Mono 10` before Inconsolata but the result was the same

**Comment by tobi-wan-kenobi** [comment] 2023-02-20 06:22
The "Nerd" font collection contains one font called "Hack for Powerline", which is what I am using.

If you have both the "nerdfonts" package and plain Inconsolata installed, you *might* need to specify "Inconsolata for Powerline" as font.

The error in your screenshot indicates your font is missing some glyphs/characters. That, in turn, means the font is not a powerline patched one. Please try installing the nerdfont package and using a "... for Powerline" font.

Hope that helps!

**Comment by airpods69** [comment] 2023-02-20 06:53
I changed it to this but seems like it didnt work. Could you mention the packages? (For arch, I suppose you are using that as well)

bar config:
```
bar {
	font pango: Inconsolata for Powerline 10
 #    mode hide
 #    hidden_state hide
    modifier $Mod
	position top
	tray_output none
	status_command bumblebee-status -m hostname nic cpu \
		memory battery brightness date time \
		-p time.format="%H:%M" date.format="%a, %b %d %Y" brightness.step=5 \
		-p battery.warning=30 \
		-t nord-powerline
}
```

**Comment by tobi-wan-kenobi** [comment] 2023-02-20 07:31
I use the AUR package nerd-fonts-git, but please be aware it is quite a big download (around 8gb, i think)

alternative is to follow the nerd-font instructions to install manually

**Comment by airpods69** [comment] 2023-02-20 08:15
I'll try installing the AUR package (nerd-fonts-git) 
Lets see how it goes since nerd fonts are supposed to be downloaded individually from their website
