### ISSUE TITLE
dnf Module starts multiple processes blocking each other 

### ISSUE THREAD

**Issue by Yali0n** [tobi-wan-kenobi/bumblebee-status#692] opened 2020-08-26 09:38 UTC
#### Description
Affected module: dnf
Version used: latest>

<description>

#### How to reproduce
Run Bumblebee with dnf module

you are getting multiple /usr/bin/pathon3 /usr/bin/dnf updateinfo processes - every 5 seconds a new one

also using dnf.interval makes no difference.

I also have an old version of bumblebee-status with latest commit 9236b5279ecd2a6a7777c61b4053ab5b031e7ab9 - from 2019/12 - there dnf is working without any issue...

**Comment by tobi-wan-kenobi** [comment] 2020-08-27 18:05
Hm, that is strange. At least using `interval` should alleviate the issue. Is it possible that the problem is that the parameter now gives the interval in seconds, not in minutes anymore? That, unfortunately, is a non-backwards compatible change that slipped in.

**Comment by tobi-wan-kenobi** [comment] 2020-08-27 18:06
Also, I have added a small fix that simplified the threading, maybe that fixes the problem for you. Please let me know whether it helps.

**Comment by Yali0n** [comment] 2020-08-28 08:12
Hi and thank you for your fast response!

It seems there is still a small issue. 
First i get the widget output - then it says "dnf error: name 'widget' ist not defined "

~/src/bumblebee-status/bumblebee-status -m dnf
{"version": 1, "click_events": true}
[
[{"full_text": " dnf 0/0/0/0 ", "color": "#aabbcc", "name": "dnf", "instance": "cfa61cf7-84b3-4b68-8cd9-b06b05944e18", "_raw": "0/0/0/0", "_suffix": " ", "_prefix": " dnf ", "align": null}],
[{"full_text": " dnf 0/0/0/0 ", "color": "#aabbcc", "name": "dnf", "instance": "cfa61cf7-84b3-4b68-8cd9-b06b05944e18", "_raw": "0/0/0/0", "_suffix": " ", "_prefix": " dnf ", "align": null}],
[{"full_text": " dnf 0/0/0/0 ", "color": "#aabbcc", "name": "dnf", "instance": "cfa61cf7-84b3-4b68-8cd9-b06b05944e18", "_raw": "0/0/0/0", "_suffix": " ", "_prefix": " dnf ", "align": null}],
[{"full_text": " dnf error: name 'widget' is not defined ", "color": "#aabbcc", "name": "dnf", "instance": "82b4882c-d35d-4d72-b887-625aa083306a", "_raw": "error: name 'widget' is not defined", "_suffix": " ", "_prefix": " dnf ", "align": null}],
[{"full_text": " dnf error: name 'widget' is not defined ", "color": "#aabbcc", "name": "dnf", "instance": "82b4882c-d35d-4d72-b887-625aa083306a", "_raw": "error: name 'widget' is not defined", "_suffix": " ", "_prefix": " dnf ", "align": null}],
[{"full_text": " dnf error: name 'widget' is not defined ", "color": "#aabbcc", "name": "dnf", "instance": "82b4882c-d35d-4d72-b887-625aa083306a", "_raw": "error: name 'widget' is not defined", "_suffix": " ", "_prefix": " dnf ", "align": null}],

**Comment by tobi-wan-kenobi** [comment] 2020-08-28 12:03
@Yali0n My apologies, I did not test sufficiently. This should be fixed now, I hope your issue is resolved.

**Comment by Yali0n** [comment] 2020-08-28 13:37
Now it's working!
Only thing i recognise is that every second a new process dnf updateinfo is spawned. Looks like the interval ist not working at all

**Comment by tobi-wan-kenobi** [comment] 2020-08-28 15:09
seems like c77f3aa broke the partial redraw completely. will investigate and add a fix soon. thanks for noticing!

**Comment by tobi-wan-kenobi** [comment] 2020-08-28 15:14
Hope this fixes all issues now. Thanks again for reporting, that was a big one :)

**Closed** 2020-08-28 15:13 UTC
Labels: bug

**Comment by Yali0n** [comment] 2020-08-30 15:28
Thanks for writing this awesome statusbar! love it

**Comment by tobi-wan-kenobi** [comment] 2020-08-30 16:04
Thanks a lot for the kind words, this kind of feedback motivates me very much!
