### ISSUE TITLE
Help with getting things up and running in sway

### ISSUE THREAD

**Issue by andrewschott** [tobi-wan-kenobi/bumblebee-status#725] opened 2020-10-09 22:11 UTC
If I use the status bar config block below, I just get the bar (which does show up) with in the right corner "[error reading from status command]".  This works perfectly in i3.  What am I missing here?  I couldn't locate anything of clear use in the sway docs, or yours, or in the other issues here (or there for that matter).  

And of course there is the obvious cause -- brain damage.

My bar section (slightly redacted):
```
bar {
  status_command bumblebee-status \
            -m sensors2 spacer load spacer memory \
                 spacer pasink pasource spacer spacer weather \
                 spacer indicator spacer time system \
            -p weather.location=redact,ed weather.showcity=true \
                weather.unit=imperial \
                weather.apikey=redacted \
            sensors2.chip_field_include=coretemp-isa-0000.temp1,amdgpu-pci-0100.temp1 \
            time.format="%d %b %Y - %I:%M:%S %P" \
            indicator.include=capslock,numlock,scrolllock \
            -t dracula-powerline
  
  position top
  
  font pango: Liberation Mono Bold 9
}
```

Thanks much!
Andrew.

**Comment by tobi-wan-kenobi** [comment] 2020-10-10 13:01
Can I close this as a duplicate of #724?

**Comment by andrewschott** [comment] 2020-10-10 16:53
Didnt realize double post.  Odd.  Thanks.  I can close it.

**Closed** 2020-10-10 16:53 UTC
