### ISSUE TITLE
Some icons appear properly in awesome-font.json but not in bar?

### ISSUE THREAD

**Issue by harsh-98** [tobi-wan-kenobi/bumblebee-status#364] opened 2019-02-19 13:05 UTC
|    Q        |   A
|------------ | -----
| Version     | x

#### Support Question
Date and disk icon appear properly in awesome-fonts.json but are prefixed and suffixed by gibberish when on bumblebee-status.
I have installed awesome-font.

**Comment by tobi-wan-kenobi** [comment] 2019-02-19 18:56
Hi,

what font are you using in the i3 bar configuration? That one also has to support the Font Awesome icons (or provide them as fallback). Personally, I've had good experience with Inconsolata and Hack.

**Comment by harsh-98** [comment] 2019-02-20 23:35
for i3bar, i am using Inconsolata.

**Comment by tobi-wan-kenobi** [comment] 2019-02-22 14:24
Hm, not sure where that comes from. Is your distribution using Awesome Font 4 or 5? I know that in version 5, some icons that were previously free, were moved to the non-free version.

Could you please tell me which icons are affected?

Thanks and sorry for the inconvenience!

**Comment by tobi-wan-kenobi** [comment] 2019-03-01 14:14
Closed due to timeout. Please reopen if the issue still persists. Thanks!

**Comment by milgner** [comment] 2019-06-15 14:46
I seem to be experiencing the same problem, running `bumblebee-status` inside a Sway bar.
Most icons are fine, but the clock and Spotify icons are pre- and suffixed by some broken glyphs.

![Screenshot](https://user-images.githubusercontent.com/160025/59552898-07785c80-8f8d-11e9-900d-e7d83e98b0ec.png)

**Comment by tobi-wan-kenobi** [comment] 2019-06-20 11:53
@milgner  Can you please let me know which font you are using in the bar configuration and whether he same issue occurs also with other fonts (e.g. Inconsolata or Hack)

Also, the distro you are using and the awesome-font version you are using might be helpful.

Thanks a lot in advance!

**Comment by GNUke** [comment] 2019-07-21 20:58
I'm having a similar problem, all icons except datetime and pasink appear normaly. The font's im using are: `font pango:System San Francisco Display 8, FontAwesome 10, PowerlineSymbols 10
` However, I also get the same problem using just Inconsolata. I'm using FontAwesome 4.7.0

**Comment by tobi-wan-kenobi** [comment] 2019-07-22 19:43
Weird, which OS are you on?

I'm using Arch, and both pasink and datetime work fine. Maybe the fonts are somehow specially patched.

Maybe it even depends on the minor version of FontAwesome (although at least the calendar icons should still be free in 4.7, so probably, that's not it).

**Comment by GNUke** [comment] 2019-07-22 19:54
I'm using Ubuntu 19.04, it seems like a `.` has replaced the icon in pasink and a `~` for the calendar when looking closely. I've tried multiple versions of FontAwesome and seem to get the error with every one of them. 



![image](https://user-images.githubusercontent.com/44187815/61660639-530edc00-ac98-11e9-931b-482ed54a84ef.png)

Also, for others who might come upon this issue, including "PowerlineSymbols 10" in my config as a fallback font allowed me to use more fonts that Inconsolata.

**Comment by zalloy** [comment] 2019-08-07 14:42
I just installed i3 yesterday and started experimenting with different bar setups. I've got the same issue as @GNUke has. I'm running Ubuntu 19.04 and I have FontAwesome, Powerline Fonts, and Inconsolata all up to date, but I'm getting a '.' instead of the icon for pasink and a '~' instead of the calendar icon. The other icons used for the other modules I installed are working fine. Just those 2 that have an issue.

**Comment by zalloy** [comment] 2019-08-07 18:23
Ayep, that's the one I installed. :woman_facepalming: I'll give that other branch a try and let you know how it works out. Thanks! :smiley:

**Comment by zalloy** [comment] 2019-08-07 19:07
@tobi-wan-kenobi I tried it, and nothing seems to have changed on my end. Not sure if maybe I'm doing something incorrectly. I just tried changing to that branch and restarting i3 in place, not sure if I'm missing a step here... :confused:

**Comment by tobi-wan-kenobi** [comment] 2019-08-08 17:00
@zalloy Sorry to read that, probably my fix just doesn't do anything. On the weekend, I'll try to either make it work with FontAwesome 5, or maybe add another iconset (material?).

Anyhow, since this seems to become an increasing issue, I'd like to get rid of it.

If you were willing to test changes, that'd be a big help.

**Comment by zalloy** [comment] 2019-08-08 17:17
@tobi-wan-kenobi I'm willing to help test changes, as long as you can confirm that by changing to the branch and restarting i3 to get it to reload bumblebee, that will allow me to see whether the changes have worked. I'm not nearly as familiar with Git as I'd like to be, but I'm working on it. 

I'm also doing a little tinkering on my end to see if I can come up with a fix that works. I'm also looking into other iconsets that might be useful for something like this. Material might be good for this, as I think that's free without having the paywall shenanigans.

**Comment by GNUke** [comment] 2019-08-08 17:34
Also tried this, calendar and volume icons are still not appearing but the mute icon seems to be showing now. 

I took a look through the code but couldn't determine where the icons are being defined. Could you point me in the right direction so I could make my own substitutions? 

![image](https://user-images.githubusercontent.com/44187815/62724494-1b669a80-b9e1-11e9-8a25-f7823d96da96.png)

**Comment by tobi-wan-kenobi** [comment] 2019-08-08 17:45
Thanks for testing!

The icons are in the "themes" directory, with their own subdirectory "icons":

https://github.com/tobi-wan-kenobi/bumblebee-status/blob/master/themes/icons/awesome-fonts.json

Hope that helps & thanks for your support!

**Comment by tobi-wan-kenobi** [comment] 2019-08-08 17:47
@zalloy yes, those are the right steps. Update bumblebee-status (switch branches, modify files, etc.) and reload i3 (i.e. it doesn't even need to be restarted, a reload of the config is sufficient)

Thanks a lot!

⁣Sent from TypeApp ​

**Comment by GNUke** [comment] 2019-08-08 18:12
Managed to fix it with nerd-fonts. (nf-fa-calendar, nf-mdi-volume_high, nf-mdi-volume_mute). Thanks!
![image](https://user-images.githubusercontent.com/44187815/62727030-92526200-b9e6-11e9-8243-3681aa13b5f6.png)

**Comment by tobi-wan-kenobi** [comment] 2019-08-08 18:25
@zalloy I just tried to install the Material Font from https://github.com/google/material-design-icons, switched my font spec to `font pango:Material Icons 12, DejaVu Mono 12` and everything seemed to work out of the box - maybe that is an OK solution for you?

**Comment by tobi-wan-kenobi** [comment] 2019-08-08 18:26
Also, @GNUke , I'd be happy to receive a PR if you had to change anything. I'm thinking I could have a look at your changes, and maybe make it so that it's possible to select different iconsets from the CLI.

What do you think?

**Comment by zalloy** [comment] 2019-08-08 21:39
@tobi-wan-kenobi I'm still not having any luck getting it to work on my end. I tried what you suggested, with the Material font, but no change when I restarted i3. Does that also need a modified json file, to tell it which icons to use? Was also trying to figure that out, but for some reason the icons aren't rendering correctly when I try to view the json file, and I'm not sure of the syntax I should use there. Is it the same as CSS?

I also tried installing ionicons, and adding that to the config, but had no luck there either. :confused:

**Comment by tobi-wan-kenobi** [comment] 2019-08-10 05:48
@zalloy Oh, sorry to hear that! No, I didn't use any modified JSON.

Weird about the ionicon icons, i tested those :( Maybe Ubuntu patches their fonts differently...

Could you please do two things:

1. Could you please let me know your i3 "bar" config (esp. the "font" part)? I'd like to reproc, maybe with a virtual machine that runs Ubuntu
2. Could you try to *only* specify the icon font in the i3 "bar" config? (i.e. "font Material Icons 12") If the configuration is applied correctly, the icons should be there, but the text should be gone / replaced with weird icons. If that doesn't work, the problem is that somehow, your i3 configuration is not correctly read during restart of i3, and we can dig further into that. If it works, it's a problem with what bumblebee-status is doing.

Thanks a lot in advance!

**Comment by zalloy** [comment] 2019-08-11 17:08
@tobi-wan-kenobi Here's what my bar config looks like:

`bar {
       font pango:Material Icons 12, DejaVu Mono 12, Powerline Symbols 12
      # font pango:Material Icons 12
       position top
       status_command ~/Projects/bumblebee-status/bumblebee-status -d -m cpu memory uptime pasink pulseaudio apt nic network_traffic publicip disk battery indicator system nvidiagpu redshift datetime weather $
}
`
I tried disabling the other fonts and just having Material Icons 12 enabled, but the only difference I saw there was that the powerline symbols were removed and only a `Σ` shows where the powerline symbols were used. I also noticed that if I mute my audio using the bar, I get a `ÿ` showing up.

Definitely seems like something is wonky with the fonts, just not sure what.

**Comment by anlif** [comment] 2019-09-06 09:34
@zalloy I'm having a similar issue. Ubuntu 18.04. See the attached screenshot
![bumblebee-bar-sigma-symbols](https://user-images.githubusercontent.com/800594/64417896-41439580-d09a-11e9-9843-49e20add0bd3.png)

**Comment by anlif** [comment] 2019-09-09 11:20
@anlif fixed this issue by installing powerline fonts manually https://github.com/powerline/fonts and configuring i3 to use a powerline font:
`font pango: Inconsolata for Powerline 20`

**Comment by Ninpo** [comment] 2019-09-25 20:33
I ran into this issue on Gentoo and the problem was resolved by installing FontAwesome version 4.7

`font pango:FontAwesome 10`

**Comment by tobi-wan-kenobi** [comment] 2019-10-20 07:54
THis seems to be related to Awesome 4 vs 5 - closing. If the issue persists, please let me know.

**Closed by tobi-wan-kenobi** 2019-10-20 07:54 UTC
