### ISSUE TITLE
Stock module broken

### ISSUE THREAD

**Issue by mschwartz** [tobi-wan-kenobi/bumblebee-status#453] opened 2019-10-11 17:39 UTC
#### Summary

Affected module: stock

Description:
Module throws an exception becuase download.finance.yahoo.com is no longer a valid host.

#### What is the current behaviour and what is the expected behaviour?

Throws error.
I expect the stock quotes to show in the status bar

#### How to reproduce

Add -m stock -p stock.symbols=VOO

#### Expected behavior
You ask for expected behavior again?

**Comment by tobi-wan-kenobi** [comment] 2019-10-11 18:41
Hi,

thanks for the report!

@msoulier Is that something you might want to have a look at? If you don't have time, I can investigate, as well.

Having said that, @mschwartz , I also agree to the point you make about the fact that the bug report template has room for improvement. But please keep in mind that the person who contributed this, did so for free in their spare time, which is true for any contribution to this software.

**Comment by mschwartz** [comment] 2019-10-11 19:10
I really appreciate this status bar.  Thanks for creating it.

I wasn’t complaining about the template, just pointing out you might want to fix it.

Regards,

**Comment by tobi-wan-kenobi** [comment] 2019-10-12 13:13
Got it, I've (hopefully) improved the bug report template. Investigating the stock issues now. Since the Yahoo API has been deprecated, that'll mean a switch to some other stock API, which might take a bit.

**Comment by tobi-wan-kenobi** [comment] 2019-10-14 18:47
Hi @mschwartz !

Mixed bag of news here:
- Good news: The module works again
- Bad news: You need to go to https://www.worldtradingdata.com and register to get a free API key (2 minutes of work, but not everyone might like this). The problem is that I didn't find any APIs that are free and don't require a key. Plus, most APIs that are free, are rate limited for a single key to a degree that it's not useful for an app (this service has 250 requests per day).

You can use it like this: `bumblebee-status -m stock -p stock.token=<registration token> stock.symbols=<comma-separated list of tokens>`

No need to specify the currency anymore, that's read directly from the API.

Hope this helps!

**Comment by mschwartz** [comment] 2019-10-14 18:51
I think there's still a free API at yahoo! that wouldn't require registering for anything...

https://query1.finance.yahoo.com/v7/finance/quote?lang=en-US&region=US&corsDomain=finance.yahoo.com&symbols=FB&fields=regularMarketPrice

**Comment by mschwartz** [comment] 2019-10-14 18:52
```
{  
   "quoteResponse":{  
      "result":[  
         {  
            "language":"en-US",
            "region":"US",
            "quoteType":"EQUITY",
            "quoteSourceName":"Nasdaq Real Time Price",
            "exchange":"NMS",
            "exchangeDataDelayedBy":0,
            "priceHint":4,
            "fullExchangeName":"NasdaqGS",
            "esgPopulated":false,
            "tradeable":true,
            "triggerable":true,
            "regularMarketPrice":0.9952,
            "regularMarketTime":1571079061,
            "sourceInterval":15,
            "exchangeTimezoneName":"America/New_York",
            "exchangeTimezoneShortName":"EDT",
            "gmtOffSetMilliseconds":-14400000,
            "marketState":"REGULAR",
            "market":"us_market",
            "symbol":"FTR"
         }
      ],
      "error":null
   }
}
```

**Comment by mschwartz** [comment] 2019-10-14 19:04
I also found this:
https://github.com/dennislwy/YahooFinanceAPI

**Comment by tobi-wan-kenobi** [comment] 2019-10-14 19:20
That's great info! I'll look into the python module later, but for now, I've tweaked the module to use the new API.

Hope this fixes your issues with the module.

**Comment by mschwartz** [comment] 2019-10-14 19:22
Outstanding!

Thanks 😀

**Comment by mschwartz** [comment] 2019-10-14 19:23
The python module might be good as a reference to the API endpoints.

I couldn’t find them documented anywhere, but they’ve been working since 2017.

**Comment by tobi-wan-kenobi** [comment] 2019-10-14 19:28
Good point, will keep that in mind.

Many thanks for your help in resolving this issue!

⁣

**Closed** 2019-10-20 07:53 UTC
